# Introduction

In many countries and regions throughout the world, human migration represents a major force of demographic, social, economic and environmental change. However, the underlying processes of migration are complex and dynamic. Research concerning these processes are challenged by weak empiric: data on the human population movements at the national, regional and international scales are of poor quality in both validity and reliability. This is especially true for data on international migration. Consequently, examination of the patterns and consequences of migration for social and environmental change is limited. Methods to estimate migration flows developed by demographers and other researchers emerge as critical tools to addressing these shortfalls in data provision and quality. Use of these tools in the analysis of patterns, trends and consequences of migration holds the potential to advance scientific understanding of social and environmental change as well as to inform domains of national, regional and international policy. The goal of this manual is to expand engagement in migration estimation and analysis using effective and robust approaches that are currently available in the public domain.

This manual covers a range of methods for handling, measuring, estimating, and visualizing migration data in R. The approach is designed for migration measured at national, regional and international levels. These methods are based on several authoritative sources, including the UN DESA manuals on [*Methods of measuring internal migration*](https://www.un.org/en/development/desa/population/publications/manual/migration/measuring-migration.asp) and [*Preparing migration data for subnational population projections*](https://www.un.org/en/development/desa/population/publications/manual/migration/subnational-migration.asp), as well as the migration chapters of the IUSSP [*Tools for Demographic Estimation*](http://demographicestimation.iussp.org/content/migration). Additionally, recent developments in the population sciences and migration studies are included. By the end of engagement with this manual, you, the reader, will have a comprehensive understanding of the various methods available for working with migration data in R, and how to apply them to empirical research, both academic and policy oriented.

To make the most of this manual, we assume that you have basic knowledge of and experience in using R, and in particular, the *tidyverse* set of R packages. If you are not familiar with R or need a refresher, we recommend working your way through an online course before diving into this manual. Some good resources for learning R and the tidyverse include:

-   [*R for Data Science*](https://r4ds.had.co.nz/), a comprehensive guide to data science in R, covering data import and cleaning, data visualization, and statistical modeling.
-   [*DataCamp*](https://www.datacamp.com/), an online learning platform that offers interactive courses on R programming and data science topics.
-   [*R Bootcamp*](https://r-bootcamp.netlify.app/), a free online course that covers the basics of R programming and the tidyverse.
-   [*Tidyverse.org*](https://www.tidyverse.org/learn/), a website dedicated to the *tidyverse* packages with tutorials, articles, and other resources for learning and using them.
-   [*Swirl*](https://swirlstats.com/), an interactive learning platform within R that teaches you how to use R in a hands-on manner.

These resources provide a comprehensive introduction to R programming and the tidyverse, which will be useful throughout this manual and in your future data analysis work.

The manual is organized into 11 chapters, each covering a different aspect of migration data analysis at the aggregate level using R. Chapter 2 provides an introduction to migration concepts and definitions. Chapter 3 focuses on the general approach to organizing migration data in R. Chapter 4 covers summary migration measures and indices. Chapter 5 is dedicated to estimating net migration totals. Chapter 6 focuses on describing and estimating migration age structures. Chapter 7 covers methods for describing bilateral migration flows. Chapter 8 covers methods for estimating bilateral migration flows. Chapters 9 and 10 cover methods for visualizing bilateral migration, including chord diagrams and Sankey plots. Finally, the manual ends with a conclusion and discussion of how the methods could be expanded and further developed in Chapter 11.

In each chapter, we provide code and data that will allow you to replicate the outputs we present, as well as exercises that will allow you to apply and practice the concepts and methods on your own. Solutions to these exercises are provided so you can check your work and ensure that you have a firm grasp of the material before moving on to the next chapter. By following the examples and completing the exercises in this manual, you will gain a deep understanding of how to handle, measure, estimate, and visualize migration data in R. Exercises have been developed to illustrate the range of possible applications of these tools of migration analysis.
