# Migration Concepts

Within the range of forms of human mobility, migration is generally considered to a process that involves a significant change in the place of residence. There are two key dimensions that distinguish migration from other types of human movements and these are time (duration) and space (between places). That is, the process of migration involves moving to a place for an amount of time that is considered of a significant length and across a distance that is considered far -- both aspects make the move significant and life changing. By life changing, we mean the person who in moving to a new place alters they way they interact with the place from which they moved. In other words, migrations are movements that change the social circumstances of the individual. It is an event that is distinguishable from other types of moves that are short duration (such as tourism or family visits) or short distance (residential mobility). Of course, both the duration and spatial dimensions of migration may be culturally defined, meaning that the processes of migration may differ between countries at a given spatial scale and at different times in terms of what constitutes as significant .

In terms of practical measurement, the United Nations recommends that migration be linked to population change, where the place where one lives is defined as a place where the person 'usually resides' withing a given year. Excluded from the measure of migration are groups, such as seasonal migrants, who live in two or more places during the course of a year, and nomads, who do not have a fixed place of residence. Further, migration is often measured as the crossing of a boundary (as opposed to a threshold of distance), whether it be an internal administrative boundry or an international border (@UnitedNations1983). Migration can be measured using various units of measurement, for example, individuals, families, or households, and national or domestic migration may be measured at different geographic scales depending on the types of administrative units that are applicable, for example, provinces, states, counties, cities and villages. Different individual / household groupings and spatial scales can have large influences on the patterns that emerge from our analyses.

Thus, specification of both spatial and temporal dimensions is required in the operational definition of migration used in analysis. Moreover, unlike other demographic processes such as fertility and mortality that have biological dimensions related to age, migration is a process and event that can occur multiple times over the course of the entire lifetime of a person or household.

## Spatial

### Usual Residence

Central to the spatial dimension of defining a migration event is the concept of place of residence, used to determine the migrants origin and destination locations. The *Principles and Recommendations for Population and Housing Censuses* (UN Statistics Division 2008: 102, para. 1.463) defines usual residence as follows:

1.  The place at which the person has lived continuously for most of the last 12 months (that is, for at least six months and one day), not including temporary absences for holidays or work assignments, or intends to live for at least six months;

2.  The place at which the person has lived continuously for at least the last 12 months, not including temporary absences for holidays or work assignments, or intends to live for at least 12 months.

The use of two alternative criteria leaves some degree of ambiguity, where the subtle differences in each definition has potentially significant implications for the measurement of migration. Further, within either of these criteria they might be additional ambiguity if the migration data source refers to migrant intentions as opposed to the measurement of actual migration behavior: take for example, at the point of data collection, persons on short-term work assignments might have intentions to stay for only a few months, but the actual work assignment may evolve into a longer stay of many months.

Spatial criteria regarding distance are also included in migration definitions (@Lee1966). e Following migration scholarship as well as international statistical recommendations, we advocate generally distinguishing between short distance / local moves, such as within cities or labor markets, and those that are considered longer distance (between cities or labor markets). There are important distinctions to be made between local mobility and migration that make their separation worthwhile: local mobility isdriven primarily by household factors while migration is driven by economic and social network factors. As with temporal criteria for defining migration. spatial criteria will reflect the specific sources of data being used for the analysis of migration which in turn reflect national statistical practices as well as specific research objectives. It is important to note, however, that the methods covered in this manual can be used to analyse and estimate both longer term migration as well as short term mobility.

Countries with the benefit of population registration systems have the opportunity to measure distance of move directly by comparing address information on points of origin and destination and thus tabulate moves by the distance covered.However, in countries without population registers or the statistical means or (time consuming) resources to tap the potential of registration system, administrative or political units into which the country is divided are often used as proxies for measuring significant distance. Thus, migration is operationally defined as a change of residence from one civil division to another. It is essential to appreciate that the volume of migration is then a function of the size and even shape of areas chosen for compilation, where typically larger administrative units, such as a province or country, have a higher volume of migration compared to smaller units like cities or counties. Using larger geographic units can result in a loss of detail and accuracy in migration data. For instance, if a state is used as the unit of compilation, it may not capture migration patterns between different cities within the state, which could be important for local policy-making. On the other hand, using smaller geographic units such as census tracts may result in too much detail, making it difficult to draw broader conclusions about migration trends at the regional or national level. Most national statistical systems countries typically have hierarchies in their administrative units and provide some internal migration data to reflect one or more of these geographies.

### Migration Data Types

A demographic perspective often distinguishes between migration stock and flow. Migration flows are migration events that occur over time and over the course of a person's life. Flows reflect individual (or household behavior) and, when compared to a 'population at risk' of experiencing migration, can be the basis for computing migration rates for a population (to be discussed further in Chapter 4. Population stock, or in our case, migration stock, are characteristics measured at the aggregate level, for example, approximately 3% of the world's population are international migrants! (again to be discussed below). Each of these migration concepts are best measured using specific data sources.

There are two main sources of data on migration flows which data and they, to a large extent, determine the types of migration that are analysed and used in demographic estimation and projections. The two main sources are administrative registers and population registration systems and national census and survey questionnaires. Administrative and population registers measure migration events continuously occurring over time. They record change in residence , analogous to registration of vital events such as births, deaths, marriages, etc. . Thus, the number of persons who have migrated within a year can be calculated as the sum of all recorded moves that occurred in that year. Often there are no duration qualifications so potentially persons can have multiple or return moves within a given year. Censuses and surveys, in contrast, are conducted at essentially one point in time, and generate cross-sectional information on population characteristics. Census and surveys , typically have retrospective questions on place of usual residence that can be cross tabulated with questions on place(s) of residence at a previous time, usually one or five years prior to the time of the census or survey. . Cross tabulations between place of residence one or five years ago with place of current residence represent migrant transitions. With these data, we do not know the exact date of the move, only that a move has occurred between two points in time. We do not know whether the move occurred 10 months ago or one week ago. Migrations followed by return within the same interval, in this example, five years, will be mixed in retrospective questions.Other types of migration data are occasionally collected in census and survey instruments that do not involve the origin location of a migration, including the duration at residence, number of moves over a given interval, and country of citizenship.

Lifetime migration data is another common type of migration data that can be generated from both administrative and population registers and cross-sectional data - censuses and surveys. . Similar to migrant transition data described above, lifetime migration is measured through cross tabulation between current place of usual residence and original place of birth. However, these data are not considered a type of flow data. Instead, they are considered migrant population stock data, and constitute a population characteristic at one point in time. With these data, we do not know a time or period when the person migrated or how often and where, only that they have migrated at least once since birth. Of course, only persons surviving to the time of the census or survey would be included. In spite of these pitfalls, national censuses in particular and surveys are critical sources of data on migration and are critical to comparative analysis of migration among populations. For the measurement of international migration, stock data have been gathered and tabulated from most countries in the world by the United Nations and World Bank and are widely used to study the cumulative effects of international migration.

### Migrant Transition Data

Migrant transition data are a key element of migration analysis and estimation and are typically collected in national censuses, which identify migrants by comparing their place of usual residence at the time of enumeration ($t$) with that at a specified earlier date ($t-n$). This type of data provides information on the movements of migrants over a given time period, which is usually either 1 year (e.g. UK) or 5 years (e.g. USA). In terms of limitations, as mentioned above, migrant transition data fail to identify multiple and return moves, which can lead to an underestimation of the true level of migration. Additionally, migrants who are born or who die during the measurement period are not counted. For example, a baby born three years ago would not have a place of usual residence five years ago. Surveys may also be used to gather migration data but the sample size must be sufficient to capture what is usually a small proportion of the population making a residential transition. In any given year, the vast majority of the population do not migrate domestically, let alone internationally.

In migrant transition data, a migrant is a person who has experienced one or more migrations during a period measured retrospectively. It is important to note that persons who moved during the measurement interval and subsequently died before its end should technically be counted as migrants and their moves as migrations. However, in practice, such cases are usually unknown or excluded, as the information is usually obtained at the end of the time interval and with reference to persons who are alive at that time. Similarly, with international migration, censuses can be used to measure immigrant transitions but not emigrant transitions. The reason is that the current place of residence is in country not gathering the census data. Censuses and surveys have been used to ask questions about family members who have emigrated but if the whole family migrated, then again, censuses would not capture them.This so-called network or multiplicity approach to measuring individual and household migration and emigration is an area of ongoing exploration by migration researchers.

### Migation Event Data

Migration event data record all moves made by individuals included in an administrative system or a population register. Depending on the purpose and characteristics of the registration system, data are available for multiple and return moves, as well newborn moves, and moves immediately before death, and moves among households, for example, for marriage. Ideally, moves come from a centralised population register, however, other registers that do not necessarily cover the whole population may be used for migration analysis. For instance, some countries require persons to register with local health clinics when moves are made, others may use tax file reports with updated address information as sources of moves. Other administrative registers address enrollment in schools and or voting registrations. As we consider below, it is important to appreciate the critical relationship between migration event data and the total resident population for the analysis of patterns and use in demographic measurement and estimation models.

While registers tend to provide a more complete record of migration over time, they may not be inclusive of the whole population, for example, military personnel and prisoners may not be included in registers of the national 'noninstitutional' population. .There may be instances where people do not register initially or fail to de-register with departing or changing status. For example, a common problem with health registration data is young adults (especially males) only register when they see a doctor (which may be several years after the move) or they do not register in their new place of residence, but continue to visit the health clinic serving their parental home. . Another issue is that geographical units adopted in administrative registers are generally larger, often regional, , and registers often fail to capture within-region moves. Additionally, administrative registers often do not include information about the characteristics of migrants outside age and sex.

## Temporal

### Migration Interval

At the population level, migration is a continuous process that occurs over time. To study the propensity or rate of migration, data must be compiled with reference to specific periods of time. These time periods can be either definite or indefinite. Definite interval data are typically collected over fixed-term periods such as one year, five years, ten years, or, in the context of national census-taking, intercensal periods. Indefinite interval data such as lifetime migration measures or data based on place of last residence lack a definite time reference as age or time at the current residence varies by each individual migrant.

The comparability of migration data with different definite time intervals can be prohibitively complicated. Commonly described as the 'one-year / five-year problem,' observed migration data consistently show that the number of migrants recorded over a five-year interval is far less than five times the number recorded over a one-year interval. In addition, the ratio of migrants between a five-year period and a one-year period is not constant, where variations occur depending on multiple factors such as the intensity and type of migration both over time and in each place of origin and destination. Consequently, there is no straightforward algebraic (mathematical?) solution to comparing one-year and five-year migration probabilities @Rogerson1990.

Issues of temporality in migration data are particularly challenging for international comparison. Countries measure international migration (immigration and emigration) for their own national policy and administrative purposes, often embedded registers and data systems. The result is great variation among national practices in international migration statistics. While the United Nations recommends measures that are aligned with changes in the country of usual residence, the reality is that countries may differ greatly, ranging from, say, no defined time period, three months, six months, or 12 months. Some countries with more effective border control practices to track all entries and exits are able to generate statistics with great temporal detail and acccuracy. In Australia, for example, an immigrant is someone who was previously living abroad and stays in the country for 12/16 months. Similarly, an emigrant is someone who has been outside Australia for 12/16 months. In contrast, some countries, especially in Eastern Europe, have population registers that rely on the notion of a 'permanent' residence, implying that persons leaving (entering) will never return (leave). Reliance on the concept of 'permanent residence' results in gross undercounts of the true levels of migration. (Cite MIMOSA / IMEM papers)

## Migration Measures

Migration measures are used to quantify the magnitude, direction and pace of population movements between places at different geographic scales. . These measures provide important insights into the demographic and social characteristics and dynamics of populations. There are several different types of migration measures that are commonly used in both research and policy analysis and evaluation. ach measure embodies its own analytic strengths and limitations; each should be used in relationship to the general and specific goals of the research project or policy analysis.

One of the most common migration measures is the migration rate or migration intensity. A migration rate or intensity is defined as the number of migrants observed during a period of time divided by the mid-year population (or average population 'at risk' of migration). The migration rate can be calculated for different migration types discussed above, such as one year or five years, and maintaining the same measure, can be used to compare migration across different places or regions. It is important to note that the probability of migration is different from a rate in just how the 'at risk' population is defined. In a rate, the population at risk is the mid-year (average) population, whereas in probability, the population at the beginning of the time interval is used as the population at risk.

Other migration measures derive from the perspective of population and migration stock discussed above. Using stock data, the count of the number of migrants is the basis for measuringthe migrant proportion. The migrant proportion is the share of the population that has migrated, measured at one point in time, for example, x% of the national population born outside of the country (using lifetime migration data). These measures can be useful for identifying patterns in migration behavior, such as the prevalence of long-distance migration or the likelihood of migration among certain social demographic groups -- males and females, working ages and youth. In demography, denominators of measures are critical. For example, some analysts would argue that in the study of international migration there is no such thing as a in-migration or immigration rate since the 'population at risk consists of (all!) national populations beyond the country of interest. Rather these measures of immigration are simply ratios that compare the number of migrants to the size of the receiving population. This problem does not exist for out-migration rates or emigration rates since both have clear populations at risk of onward migration.

As you are no doubt aware, all migration measures are affected by data quality, such as underreporting of migrants (reliability issues) or errors in place of residence information (validity issues)These problems tend to increase as the data become more detailed in terms of intricacies in definitions of migrants and migration.

Additionally, different measures may be more appropriate for different research questions or policy applications. For example, the migration rate may be more useful for understanding the overall magnitude of migration in the population, while the count of migrants can provide a basic understanding of the scale of migration patterns over time and between different spatial units with implications for programs supporting the needs of migrants in specific places

Migration measures can be defined at different levels of detail, ranging from region-to-region measures, to region totals, to system totals or index measures. Region-to-region measures capture the flow of migrants between two specific regions, while region totals capture the total number of migrants coming in or going out of a specific region. System totals, or index measures, provide an overall picture of migration within a given system or country, which we will discuss in more detail in the next chapter.

### Region-to-region

We now move this discussion of migration measures and indices to consider region-to-region migration using measures represented by R notation.

Region-to-region migration, also known as *bilateral* migration, migration *streams* or *origin-destination* migration, refers to a migration measure that cross-classifies region of origin by region of destination, forming a matrix of $n \times (n-1)$ streams along each origin-destination combination, where $n$ represents the number of regions. The set of region-to-region migration measures can be represented by $m_{ij}$, where the sub-scripts $i$ and $j$ represent the same set of regions for each origin-destination combination. The set of bilateral migration flows provide a basis to assess the comparative volumes and directions of migration between a set of regions.

The *gross interchange* represents the total number of migrants moving between a particular pair of regions, for example, $m_{ij} + m_{ji}$. The *net migration steam* or *bilateral net migration* represents the difference in migration between a pair of region i.e. $m_{ij} - m_{ji}$.

For a pair of streams that are of unequal size, where the net migration stream is not close to zero, there exists a *dominant stream* which is far larger than the *reverse* or *counter* stream in the opposite direction.

### Region Totals

Every migration event can be considered an out-migration in relation to the region of origin and an in-migration in relation to the region of destination. As implicitly covered above, when migration events involve movement between countries , migration events are typically described as emigration and immigration, rather than out-migration and in-migration.

Totals on in- or out-migration for each region are typically used to evaluate the volume of migration to or from a particular set of regions. In some countries, data is collected or aggregated without reference to the place of origin for in-migration totals or destination for out-migration totals. Consequently the migration totals provide the most detailed measure of regional migration but with little information on the direction of the migration flows between each region. A summary of the common terms for migration totals are shown in Table 1. The in-migration (or immigration) totals can be represented by replacing the origin $i$ index with a $+$; $m_{+j}$. Similarly, the out-migration (or emigration) totals can be represented by replacing the destination $j$ index with $+$; $m_{+j}$.

For our purposes in using R for migration analysis in the next several chapters and exercises, migration totals will refer to in-migration and out-migration, but are consistent with immigration and emigration, respectively.

| Scale         | Area        | Event Term    | Migrant Term |
|---------------|-------------|---------------|--------------|
| Internal      | Origin      | out-migration | out-migrant  |
|               | Destination | in-migration  | in-migrant   |
| International | Origin      | emigration    | emigrant     |
|               | Destination | immigration   | immigrant    |

The sum of the in-migration and out-migration totals ($m_{i+} + m_{+j}$) provides the migration *turnover* of each region. Net migration totals provides a balance of movements in opposing directions from the difference between in-migration and out-migration ($m_{+j} - m_{i+}$). Net migration measures are more typically obtained via demographic accounting, as a residual from the differences in population change, births and deaths over a period in each region. As this calculation does not require expensive migration data collection systems, net migration measures are one of the most common forms of migration measures.

Net migration measures, however, have a number of notable drawbacks for migration analysis, as highlighted by @rogers1990rnm. In particular, net migration does not enumerate migrants themselves, but instead follows a residual of in-migrants and out-migrants. (there is truly no such thing as a 'net migrant'!) Consequently, the social and behavioral dynamics related to the observed migration patterns can be missed. For example, a net migration of -100 might involve a region receiving no in-migrants and sending 100 out-migrants or receiving 1,000,000 migrants and sending 1,000,100 out-migrants. Further migration dynamics are also missed when looking at net migration rates (discussed in the next section) and regularities in age profiles of migration (discussed in Chapter X) are often preceded when using age-specific net migration measures.

### Rate measures

Migration rates are important indicators for understanding the dynamic nature of population movements - over time and for comparison among places. Out-migration (or emigration) rates are calculated by dividing the number of out-migrants or emigrants during a specific period by the population exposed to the likelihood of migration. This is represented by the formula:

$$
e^{[t, t +1]} = \frac{E^{[t, t +1]}}{P}k
$$

Here, $e^{[t, t+1]}$ represents the out or emigration rate, $E^{[t, t +1]}$ is the number of out-migrants or emigrants during the period, $P$ is the population exposed to the likelihood of migration, and $k$ is a constant, often set as 1000. The exposure population can be the population at the mid-interval, assuming migration is evenly distributed, or the population at the start or end of the interval if migration has a negligible effect on population change. Additionally, out-migration rates can be further decomposed by subsets of the population, such as age or sex:

$$
e^{[t, t +1]}_{i} = \frac{E_{i}^{[t, t +1]}}{P_{i}}k
$$

On the other hand, in-migration (or immigration) ratios are calculated by dividing the number of in-migrants or immigrants by the population not exposed to the risk of migrating into the region. The formula for in-migration ratio is:

$$
i^{[t, t +1]} = \frac{I^{[t, t +1]}}{P}k
$$

Similarly, net migration ratios are calculated by dividing the net migration (difference between in-migration and out-migration) by the population not exposed to migration risk:

$$
m^{[t, t +1]} = \frac{M^{[t, t +1]}}{P}k
$$

To underscore our previous point, , in-migration and net migration ratios are different from demographic rates because they use the resident population in the denominator, which is not a valid 'population at risk.'. This approach satisfies the needs of the demographic balancing equation, as rates of gain and loss are measured relative to the same population. The demographic balancing equation is expressed as:

$$
\begin{aligned}
P^{t+1} &=  P^{t} + B^{[t, t +1]} - D^{[t, t +1]} +  M^{[t, t +1]} \\
P^{t+1} &=  P^{t} \left(1 + b^{[t, t +1]} - d^{[t, t +1]} +  m^{[t, t +1]} \right)\\
&= P^{t} \left(1 + b^{[t, t +1]} - d^{[t, t +1]} +  i^{[t, t +1]} - e^{[t, t +1]} \right)
\end{aligned}
$$

where $P^{t+1}$ is the population at the next time point, $b^{[t, t+1]}$ and $d^{[t, t+1]}$ represent births and deaths during the period, and \$i\^{\[t, t+1\]} \$ and $e^{[t, t+1]}$ denote in-migration and out-migration rates. Net migration $M^{[t, t+1]}$ can be substituted with the difference between in-migration and out-migration $I^{[t, t+1]} - O^{[t, t+1]}$. The equation can be simplified as:

$$
\begin{aligned}
P^{t+1}&= P^{t} + B^{[t, t +1]} - D^{[t, t +1]} +  I^{[t, t +1]} - O^{[t, t +1]} \\
&= P^{t} \left(1 + b^{[t, t +1]} - d^{[t, t +1]} +  i^{[t, t +1]} - o^{[t, t +1]} \right)
\end{aligned}
$$

This formulation allows for the analysis of population change considering the effects of births, deaths, in-migration, and out-migration.
