# Preface {.unnumbered}

In many countries and regions throughout the world, migration is becoming or already is the largest component of population change and represents an important mechanism for social, economic and environmental change.  Migration data, however, are too often of poor quality, missing or provided without disaggregation by basic demographic characteristics such as age and sex. Methods to estimate migration flows have been developed by demographers and other researchers to help address shortfalls of extant population data sources and provide a platform to better understand patterns, trends and consequences of migration dynamics at different geographic scales. This manual considers methods for measuring, estimating and visualising migration flow data between populations, and their implementation using R. Readers will become familiar with useful R functions for handling migration data, a range of measures to summarise and compare migration systems, common estimation methods to overcome inadequate or missing migration data, and recently developed methods to visualize complex migration patterns.  Code samples and exercises are provided throughout the manual. While not a requirement, readers would benefit most from these illustrative applications if they have some prior knowledge in how to handle and plot data using the tidyverse set of R packages.
